version: "2.1"

services:
  summariser:
    container_name: summariser
    build: .
    command: python3 ./main.py
    volumes:
      - ./output_summaries:/news_summariser/output_summaries
      - ./db:/news_summariser/db
      - ./log:/news_summariser/log
      - ./transformers:/root/.cache/torch/transformers
    ports:
      - "5000:5000"
    restart: always
