# Download base image
#FROM continuumio/miniconda3
FROM arm32v7/python:3.7.10-buster

# Create the folder where all code, dependencies and models will be put
RUN mkdir /news_summariser
# Download GloVe model
RUN wget http://nlp.stanford.edu/data/glove.6B.zip

# Install unzip
RUN apt-get update && apt-get -y --no-install-recommends install unzip gcc g++
# Unzip it
RUN unzip glove.6B.zip -d /news_summariser/glove.6B
# Remove the original file just for saving ~ 800 MB
RUN rm -rf glove.6B.zip
# Copy environment
# Add conda-forge among available channels
#RUN conda config --append channels conda-forge
RUN wget https://www.piwheels.org/simple/scipy/scipy-1.7.2-cp37-cp37m-linux_armv7l.whl#sha256=c0356d0f3117dc75971ef39aa7b9d63226a59329cce85fc075d80004ff195587
RUN pip install scipy-1.7.2-cp37-cp37m-linux_armv7l.whl
# Create environmentRUN conda env create -f /news_summariser/environment.yml
RUN apt-get install gfortran libatlas-base-dev libopenblas-dev liblapack-dev -y
RUN pip install scikit-learn --index-url https://piwheels.org/simple
ADD requirements.txt /news_summariser
RUN pip --default-timeout=1200 install -r /news_summariser/requirements.txt
# Copy code in the appropriate directory
ADD src /news_summariser/src
# Create directories where summaries, logs and parsed articles will be saved
RUN mkdir /news_summariser/output_summaries /news_summariser/articles_db /news_summariser/log
# Create volumes for being able to access logs, summaries and DB from the outside and for not losing them
VOLUME /news_summariser/output_summaries /news_summariser/db /news_summariser/log /root/.cache/torch/transformers
# Change workdir
WORKDIR "/news_summariser/src"
# Let the music play :)
#ENTRYPOINT ["conda", "run", "-n", "summariser"]
